# Doc2Vec Configuration
embedding:
  provider: 'openai'
  dimension: 3072
  openai:
    model: 'text-embedding-3-large'

sources:
  - type: 's3'
    product_name: 'procgen-workshops'
    version: 'latest'
    bucket: 'procgen-workshops'
    include_extensions: ['.md', '.yaml', '.sh', '.js']
    url_rewrite_prefix: ''
    max_size: 1048576
    database_config:
      type: 'qdrant'
      params:
        qdrant_url: 'https://qdrant.is.solo.io'
        collection_name: 's3-procgen-workshops'