# Doc2Vec Configuration
# Global embedding configuration (optional - can be overridden per source)
embedding_config:
  provider: 'gemini'  # or 'openai'
  gemini:
    model: 'gemini-embedding-exp-03-07'  # Default Gemini embedding model
    # api_key: 'your-gemini-api-key'  # Optional, uses GEMINI_API_KEY env var if not specified
  # openai:
  #   model: 'text-embedding-3-large'  # Default OpenAI embedding model
  #   api_key: 'your-openai-api-key'   # Optional, uses OPENAI_API_KEY env var if not specified

sources:
  - type: website
    product_name: 'ambient'
    version: 'latest'
    url: 'https://ambientmesh.io/docs/'
    max_size: 1048576
    database_config:
      type: 'sqlite'
      params:
        db_path: './ambient.db'
    # Source-specific embedding config (optional - overrides global config)
    # embedding_config:
    #   provider: 'openai'
    #   openai:
    #     model: 'text-embedding-3-large'